;; -*- lexical-binding: t; -*-

(setq use-package-always-ensure nil)

;; Default settings
(set-face-attribute 'default nil :font "Source Code Pro" :height 130)
(save-place-mode t)
(recentf-mode t)
(tool-bar-mode -1)
(setq which-key-idle-delay 0.5)
(which-key-mode t)
;; Reenable once figured out how works
;; (setq text-mode-ispell-word-completion nil)
(setq ispell-program-name "hunspell"
      ispell-dictionary "en_GB-ise")
(defalias 'shell 'vterm)

(use-package ef-themes
  :config
  (modus-themes-load-theme 'ef-kassio))

;; Auto-save, and backup directories directory
(setq autogenerated-file-directory (concat user-emacs-directory "auto-save/"))

(unless (file-exists-p autogenerated-file-directory)
  (make-directory autogenerated-file-directory t)
  (write-region "./auto-save\n"
                nil
		(expand-file-name ".stow-local-ignore" user-emacs-directory)))

;; Auto-save
(setq auto-save-file-name-transforms
      `((".*" ,autogenerated-file-directory t)))

;; Backup files
(setq backup-directory-alist
      `(("." . ,autogenerated-file-directory)))

(use-package org
  :ensure t
  :config
  ;; 1. Configure Org-Babel to support PlantUML
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((plantuml . t)))

  ;; 2. Point to your PlantUML JAR file or executable
  (setq org-plantuml-exec-mode 'plantuml)
  (setq org-plantuml-executable-path "plantuml")
  (setq org-confirm-babel-evaluate nil)

  ;; 3. Define the auto-refresh function
  (defun my/org-babel-execute-and-redisplay ()
    "Execute all babel blocks and refresh inline images."
    (when (derived-mode-p 'org-mode)
      (ignore-errors
        (org-babel-execute-buffer)
        (org-display-inline-images))))

  ;; 4. Automatically update diagrams on file save
  :hook (after-save . my/org-babel-execute-and-redisplay))

(use-package apheleia
  :init
  (with-eval-after-load 'apheleia
    (setf (alist-get 'scheme-mode apheleia-mode-alist) 'lisp-indent))
  :config
  (apheleia-global-mode +1))

(use-package magit
  :bind ("C-c g" . magit-status))

;; Completion
(use-package vertico
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode))

(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles partial-completion))))
  (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring

;; Enable rich annotations using the Marginalia package
(use-package marginalia
  ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
  ;; available in the *Completions* buffer, add it to the
  ;; `completion-list-mode-map'.
  :bind (:map minibuffer-local-map
              ("M-A" . marginalia-cycle))
  ;; The :init section is always executed.
  :init
  ;; Marginalia must be activated in the :init section of use-package such that
  ;; the mode gets enabled right away. Note that this forces loading the
  ;; package.
  (marginalia-mode))

(use-package embark
  :bind
  (("C-." . embark-act)
   ("M-." . embark-dwim)
   ("C-h B" . embark-bindings)))

(use-package embark-consult)

(use-package corfu
  ;; Optional customizations
  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-auto nil)
  (corfu-last  (corfu-popupinfo-mode t)
	       ;;(corfu-preselect first)
	       ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
	       ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
	       ;; (corfu-preview-current nil)    ;; Disable current candidate preview
	       ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
	       ;; (corfu-on-exact-match 'insert) ;; Configure handling of exact matches

	       ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
	       ;; :hook ((prog-mode . corfu-mode)
	       ;;        (shell-mode . corfu-mode)
	       ;;        (eshell-mode . corfu-mode))
	       :init
	       ;; Recommended: Enable Corfu globally.  Recommended since many modes provide
	       ;; Capfs and Dabbrev can be used globally (M-/).  See also the customization
	       ;; variable `global-corfu-modes' to exclude certain modes.
	       (global-corfu-mode)
	       ;; Enable optional extension modes:
	       ;; (corfu-history-mode)
	       (corfu-popupinfo-mode t)
	       ))

(use-package cape
  :bind ("C-c p" . cape-prefix-map)
  :init
  ;;(add-hook 'completion-at-point-functions #'cape-dabbrev)
  (add-hook 'completion-at-point-functions #'cape-emoji)
  (add-hook 'completion-at-point-functions #'cape-file))

(defun add-text-completion ()
  ;; Creates a buffer-local copy that inherits your global emoji and file backends
  (make-local-variable 'completion-at-point-functions)
  ;; Safely adds dabbrev to the front of this buffer's local list
  (add-to-list 'completion-at-point-functions #'cape-dabbrev))

(dolist (hook '(text-mode-hook org-mode-hook markdown-mode-hook))
  (add-hook hook #'add-text-completion))

(autoload 'enable-paredit-mode "paredit" "Turn on pseudo-structural editing of Lisp code." t)
(add-hook 'emacs-lisp-mode-hook       #'enable-paredit-mode)
(add-hook 'eval-expression-minibuffer-setup-hook #'enable-paredit-mode)
(add-hook 'ielm-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-interaction-mode-hook #'enable-paredit-mode)
(add-hook 'scheme-mode-hook           #'enable-paredit-mode)

;; Modal editing
(use-package meow
  :init
  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (setq meow-use-clipboard t)
    (meow-motion-overwrite-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("<escape>" . ignore))
    (meow-leader-define-key
     ;; SPC j/k will run the original command in MOTION state.
     '("j" . "H-j")
     '("k" . "H-k")
     ;; Use SPC (0-9) for digit arguments.
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("/" . meow-keypad-describe-key)
     '("?" . meow-cheatsheet))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("9" . meow-expand-9)
     '("8" . meow-expand-8)
     '("7" . meow-expand-7)
     '("6" . meow-expand-6)
     '("5" . meow-expand-5)
     '("4" . meow-expand-4)
     '("3" . meow-expand-3)
     '("2" . meow-expand-2)
     '("1" . meow-expand-1)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("D" . meow-backward-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("q" . meow-quit)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . meow-kill)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-visit)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("<escape>" . ignore)))
  :config
  (meow-setup)
  (meow-global-mode 1))

(setq epg-pinentry-mode `loopback)
(pinentry-start)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(safe-local-variable-values
   '((eval modify-syntax-entry 43 "'") (eval modify-syntax-entry 36 "'")
     (eval modify-syntax-entry 126 "'")
     (eval progn (require 'lisp-mode)
	   (defun emacs27-lisp-fill-paragraph (&optional justify)
	     (interactive "P")
	     (or (fill-comment-paragraph justify)
		 (let
		     ((paragraph-start
		       (concat paragraph-start
			       "\\|\\s-*\\([(;\"]\\|\\s-:\\|`(\\|#'(\\)"))
		      (paragraph-separate
		       (concat paragraph-separate
			       "\\|\\s-*\".*[,\\.]$"))
		      (fill-column
		       (if
			   (and
			    (integerp emacs-lisp-docstring-fill-column)
			    (derived-mode-p 'emacs-lisp-mode))
			   emacs-lisp-docstring-fill-column
			 fill-column)))
		   (fill-paragraph justify))
		 t))
	   (setq-local fill-paragraph-function
		       #'emacs27-lisp-fill-paragraph))
     (geiser-guile-binary "guix" "repl")
     (eval add-to-list 'completion-ignored-extensions ".go")
     (geiser-insert-actual-lambda))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
